### PR TITLE
(SIMP-3118) Updated simp_logstash to Logstash 5.X

### PR DESCRIPTION
**Pull request by lnemsick-simp**
- Code changes
  - Propagated logstash parameter name change ($configdir -> $config_dir)
  - Updated tcp/udp-based inputs with following settings:
      enable_metric
      id
      proxy_protocol
  - Updated elasticsearch output with the following settings:
      absolute_healthcheck_path
      enable_metric
      failure_type_logging_whitelist
      healthcheck_path
      id
      parameters
      pipeline
      pool_max
      pool_max_per_route
      resurrect_delay
      retry_initial_interval
      retry_on_conflict
      validate_after_inactivity
      version
      version_type
  - Updated file output with the following settings:
      enable_metric
      id
  - Fixed bug in input/stdin.pp whereby the content parameter was not
    properly used to generate th input plugin configuration.
  - Fixed type bug in simp_logstash::output::elasticsearch::action.  Type
    is a String (Enum) not  an Array of Strings.
  - Fixed bug in enum for simp_logstash::output::elasticsearch::script_type
  - Fixed bug in sshd grok rule for invalid user
  - Made sure firewall global catalyst is used to determine when to include
    iptables class and create iptables rules.
  - Adjusted formatting of file output's dir_mode and file_mode to be
    more user friendly (octal).
  - Eliminated trailing whitespace in most files

- Documentation changes
  - Updated comments in init.pp to reflect change from logstash::init_defaults to
    logstash::startup_options and logstash::java_options
  - Fixed puppet strings problems

- Added spec tests

- Acceptance testing updates/fixes
  - Updated YUM repo URL for elasticsearch and logstash
  - Removed OBE logstash::logstash_user and logstash::logstash_group hieradata
  - Added logic to ensure JAVA 8 is installed on el6 servers running logstash
    or elasticsearch
  - Specified provider in 'puppet resource service' actions for el6, as
    puppet assumes provider is SystemV, when in fact the provider is Upstart.
  - Added elasticsearch test suite to set of suites run by 'rake beaker:suites'
  - Minor tweaks (e.g., use of wait_for_log_message(), context/example names)
  - Pinned versions in .fixtures.yml

CAUTION! This project uses interim artifacts:
- pupmod-simp-simp_elasticsearch: Use SIMP-3048 PR from lnemsick-simp repo
  (code update to 5.X Elasticsearch) until PR is merged
- puppet-logstash: Use temporary version in lnemsick-simp repo until merge
  of elastic PR #330 ('Fixes for Puppet 4 strict_variables') is merged
  into the elastic repo and then propagated to simp fork.
- puppet-elasticsearch:  Use newer version from elastic repo for ES 5.4
  fixes, until that version is propagated to our fork.

UNADDRESSED ITEMS/ISSUES
- Did not add any of the unexposed settings to the filters, because
  unlike the inputs and outputs, the filters for the most part do
  not allow any tweaking.  The user only has the nuclear option
  to completely replace the filter content.
- Did not add id setting to each filter plugin. May want to do this
  to distinguish each grok/multiline/syslog_pri filter used in the
  set of filters.
- Did not address lack of tests for
  clean.pp, optimize.pp + curator.pp
  filter/audispd.pp
  filter/httpd.pp
  filter/puppet_agent.pp
  filter/puppet_server.pp
  filter/simp_syslog.pp
  filter/slapd_audit.pp

### CODE REVIEW

**Review by trevor-vaughan — COMMENTED** [review]
👍 Visual inspection looks fine to me.

**Review by jeefberkey — DISMISSED** [review]
Happy this has so many tests now.

**Review by lnemsick-simp — COMMENTED** [review]
clean.pp and optimize.pp need to be reworked, as the elasticsearch-curator api has changed.

**Review by lnemsick-simp — COMMENTED** [review]
Basic integration is complete.  Filters and Grafana dashboards need to be updated, but that work has been moved to a separate ticket.

**Review by trevor-vaughan — APPROVED** [review]
:+1: Looks good. Tested on Puppet 4.8 and 4.10

**Pull request merged**
