### PR TITLE
(SIMP-4009) Add support for Puppet 5 and OEL

### PR DESCRIPTION
**Pull request by jeefberkey**
SIMP-4009 #comment update simp_logstash

### CODE REVIEW

**Comment by jeefberkey** [comment]
:heavy_check_mark: https://gitlab.com/simp/pupmod-simp-simp_logstash/pipelines/28640972

**Review by trevor-vaughan — DISMISSED** [review]
This doesn't add support for OEL as noted by the title of the PR.

If you want to change it to just Puppet 5, that would be fine.

**Comment by ayohrling** [comment]
Marking this WIP temporarily. I have to push a PR upstream to the logstash module for OEL-6 setting upstart properly, but am incorporating a work-around here for now as well.

**Comment by ayohrling** [comment]
Pushed changes for the workaround for upstream. Need to still push the upstream PR and need to resolve support issues with stunnel I believe that are causing elasticsearch acceptance suite failures on OEL7

**Comment by ayohrling** [comment]
My PR upstream has been merged, I am going to check that release is good and update this code to require that version upstream.

**Comment by ayohrling** [comment]
Been digging deeper into this for a while. I finally found the actual bug that is happening; it's here: https://github.com/rsyslog/rsyslog/issues/1474 and there are no updated packages for EL7 that have this fixed; however, I have found that it seems to only be happening when the `StreamDriverPermittedPeers` legacy option is set to `el7-server.yohrling.com`. This is why I was unable to produce on the `pupmod-simp-rsyslog` acceptance tests, they have `server-N.{domain}` and `client.{domain}`. My plan is to spend a little time cleaning up the nodesets and then retest and hopefully push this afternoon.

**Comment by trevor-vaughan** [comment]
@ayohrling This may have been fixed in recent updates to the `rsyslog` module that allow for multiple domains in the `StreamDriverPermittedPeers` option.

**Comment by ayohrling** [comment]
Running into idempotency issues after changing the hostnames to not hit the random Rsyslog memory corruption error:

```
1) rsyslog client -> 1 logstash server without TLS client client-el6-> server server-el7 without TLS should configure client idempotently
     Failure/Error: apply_manifest_on(client, client_manifest, :catch_changes => true)
     Beaker::Host::CommandFailure:
       Host 'client-el6' exited with 2 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.SxoEXF
       Last 10 lines of output were:
       	Notice: Compiled catalog for client-el6.yohrling.com in environment production in 0.52 seconds
       	Info: Applying configuration version '1539616959'
       	Info: Computing checksum on file /etc/rsyslog.simp.d/00_simp_pre_logging/global.conf
       	Info: /Stage[main]/Rsyslog::Config/Rsyslog::Rule[00_simp_pre_logging/global.conf]/File[/etc/rsyslog.simp.d/00_simp_pre_logging/global.conf]: Filebucketed /etc/rsyslog.simp.d/00_simp_pre_logging/global.conf to puppet with sum 7fbe18232dc47c2f3deff8a26c155b9c
       	Notice: /Stage[main]/Rsyslog::Config/Rsyslog::Rule[00_simp_pre_logging/global.conf]/File[/etc/rsyslog.simp.d/00_simp_pre_logging/global.conf]/content: content changed '{md5}7fbe18232dc47c2f3deff8a26c155b9c' to '{md5}d5b3b112eeb7a95a3e9b619b69fb790f'
       	Info: /Stage[main]/Rsyslog::Config/Rsyslog::Rule[00_simp_pre_logging/global.conf]/File[/etc/rsyslog.simp.d/00_simp_pre_logging/global.conf]: Scheduling refresh of Class[Rsyslog::Service]
       	Info: Class[Rsyslog::Config]: Scheduling refresh of Class[Rsyslog::Service]
       	Info: Class[Rsyslog::Service]: Scheduling refresh of Service[rsyslog]
       	Notice: /Stage[main]/Rsyslog::Service/Service[rsyslog]: Triggered 'refresh' from 1 events
       	Notice: Applied catalog in 1.68 seconds
```

**Comment by trevor-vaughan** [comment]
@ayohrling I've now run this PR on 3 different systems and can't make it fail any acceptance tests so I'm calling this one good to go!

**Review by trevor-vaughan — APPROVED** [review]

**Pull request merged**
